Drop --install-dir option
This does not do what I thought it does

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,7 +41,7 @@ before_install:
 
 script:
   - bundle exec rspec spec/cli_spec.rb spec/provider_spec.rb
-  - gem build dpl.gemspec && gem install --install-dir=install dpl-*.gem
+  - gem build dpl.gemspec && gem dpl-*.gem
   - echo -e "\n${ANSI_GREEN}Run specs${ANSI_RESET}"
   - |
     spec_errors=0
@@ -60,7 +60,7 @@ script:
     for f in dpl-*.gemspec; do
       base=${f%*.gemspec}; name=${base#dpl-*}
       echo -e "\n${ANSI_GREEN}${base}${ANSI_RESET}\n"
-      gem build --silent $f && gem install --install-dir=install dpl-${name}-*.gem && ( dpl --provider=${name} --no-deploy ) || ( echo -e "${ANSI_RED}${name} invocation failed${ANSI_RESET}" && let no_err=$no_err+1 )
+      gem build --silent $f && gem install dpl-${name}-*.gem && ( dpl --provider=${name} --no-deploy ) || ( echo -e "${ANSI_RED}${name} invocation failed${ANSI_RESET}" && let no_err=$no_err+1 )
     done
     test $no_err -eq 0
   # - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem && dpl --provider=script --script='echo foo'
