Show which gem's specs failed

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -32,7 +32,7 @@ script:
       echo -e "\n${ANSI_GREEN}${base}${ANSI_RESET}\n"
       echo -e "source 'https://rubygems.org'\ngemspec :name => \"dpl-${name}\"" > Gemfile-${name}
       export BUNDLE_GEMFILE=Gemfile-${name}
-      bundle install --gemfile Gemfile-${name} --path=vendor/cache/dpl-${name} --binstubs=bin && ./bin/rspec spec/provider/${name}_spec.rb || let spec_errors=$spec_errors+1
+      bundle install --gemfile Gemfile-${name} --path=vendor/cache/dpl-${name} --binstubs=bin && ./bin/rspec spec/provider/${name}_spec.rb || ( echo -e "${ANSI_RED}${name} specs failed${ANSI_RESET}" && let spec_errors=$spec_errors+1 )
     done
     test $spec_errors -eq 0
   - echo -e "\n${ANSI_GREEN}Install gem and invoke dpl${ANSI_RESET}"
